In [2]:
#import torch, not pytorch
import torch

In [3]:
# Generally, pytorch is numpy with more ML features
# Tensor is like a kind of multi-dimensional array

# Dot product of arrays
x = torch.Tensor([5,2])
y = torch.Tensor([1,2])
print(x*y)

tensor([5., 4.])


In [3]:
# zeros matrix
a = torch.zeros([2,5])
print(a)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [4]:
# shape of array
a.shape

torch.Size([2, 5])

In [6]:
# array filled with random numbers
b = torch.rand([2,5])
print(b)

tensor([[0.5719, 0.1776, 0.7008, 0.1941, 0.6845],
        [0.9236, 0.6019, 0.9405, 0.6917, 0.5705]])


In [7]:
# reshape is differnt, here we call "view"
# we need to re-assign, instead of b.view([2,5])
b = b.view([1, 10])
print(b)

tensor([[0.5719, 0.1776, 0.7008, 0.1941, 0.6845, 0.9236, 0.6019, 0.9405, 0.6917,
         0.5705]])
